### ISSUE TITLE
FAT : Reimplement the FAT structure

### ISSUE THREAD

**Issue by chalumeau-clara** [SherlockFS/SherlockFS#6]
PB : Lorsque la FAT est pleine la fonction `create_fat()` n'est pas en capacité de rajouter d'autres FAT car l'ensemble des entrées de toutes les FAT sont pleines.

Solution : supprimer le pointeur `next_fat_table` et laisser uniquement 1 entrée de bloc libre pour une éventuelle future FAT.

Penser à reimplem les fonctions des FATs.

**Comment by nathan-rabet** [comment]
\+ modifier toutes les fonctions de SHRLKFS qui manipulent des FAT pour qu'elles prennent en compte leur chiffrement.

**Comment by nathan-rabet** [comment]
Closed by #29.
