### ISSUE TITLE
CRYPTO : Remettre le bigint RSA `e` dans le _KEYS STORAGE_

### ISSUE THREAD

**Issue by chalumeau-clara** [SherlockFS/SherlockFS#8]
Etant donné que des clés RSA n'étant pas générée par SherlockFS peuvent être réutilisées dans ce dernier, il est important de stocker la valeur entière de la clé (et pas uniquement `n` mais bien `n` et `e`).

**Comment by nathan-rabet** [comment]
Déprécié par l'issue #24.

**Comment by nathan-rabet** [comment]
Finalement, on va repartir sur ça (nous ne feront pas #24).

**Comment by nathan-rabet** [comment]
Résolu dans c0b725c.
