### ISSUE TITLE
FORMATER : Finir l'implémentation

### ISSUE THREAD

**Issue by chalumeau-clara** [SherlockFS/SherlockFS#9]
1. Initialiser le bloc `ROOT_DIR_BLOCK` avec un `memset()`,
2. Chiffrer les blocs `FIRST_FAT_BLOCK` et `ROOT_DIR_BLOCK` avec la clé AES générée.

**Comment by nathan-rabet** [comment]
Modifier toutes les fonctions de SHRLKFS qui manipulent des FAT pour qu'elles prennent en compte leur chiffrement.

**Comment by nathan-rabet** [comment]
Closed by #29.
